In [63]:
import pandas as pd

In [64]:
df = pd.read_csv('loan_data.csv')

In [65]:
df

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,1,debt_consolidation,0.12,829.10,11.35,19.48,737,5639.96,28854,52.10,0,0,0,0
1,1,credit_card,0.11,228.22,11.08,14.29,707,2760.00,33623,76.70,0,0,0,0
2,1,debt_consolidation,0.14,366.86,10.37,11.63,682,4710.00,3511,25.60,1,0,0,0
3,1,debt_consolidation,0.10,162.34,11.35,8.10,712,2699.96,33667,73.20,1,0,0,0
4,1,credit_card,0.14,102.92,11.30,14.97,667,4066.00,4740,39.50,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9573,0,all_other,0.15,344.76,12.18,10.39,672,10474.00,215372,82.10,2,0,0,1
9574,0,all_other,0.13,257.70,11.14,0.21,722,4380.00,184,1.10,5,0,0,1
9575,0,debt_consolidation,0.11,97.81,10.60,13.09,687,3450.04,10036,82.90,8,0,0,1
9576,0,home_improvement,0.16,351.58,10.82,19.18,692,1800.00,0,3.20,5,0,0,1
9577,0,debt_consolidation,0.14,853.43,11.26,16.28,732,4740.00,37879,57.00,6,0,0,1

In [66]:
df.dtypes

credit.policy          int64
purpose               object
int.rate             float64
installment          float64
log.annual.inc       float64
dti                  float64
fico                   int64
days.with.cr.line    float64
revol.bal              int64
revol.util           float64
inq.last.6mths         int64
delinq.2yrs            int64
pub.rec                int64
not.fully.paid         int64
dtype: object

In [67]:
df.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [68]:
df.groupby('purpose')[['int.rate','installment']].mean()

                    int.rate  installment
purpose
all_other               0.12       244.94
credit_card             0.12       319.50
debt_consolidation      0.13       358.98
educational             0.12       217.55
home_improvement        0.12       337.07
major_purchase          0.11       243.48
small_business          0.14       433.83

In [69]:
import numpy as np

In [70]:
df['ingreso_real'] = np.exp(df['log.annual.inc'])

In [71]:
print(df[['log.annual.inc', 'ingreso_real']].head())

   log.annual.inc  ingreso_real
0           11.35      85000.00
1           11.08      65000.00
2           10.37      32000.00
3           11.35      85000.00
4           11.30      80800.00

In [72]:
df.sort_values('ingreso_real')

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,ingreso_real
7822,0,debt_consolidation,0.17,64.38,7.55,18.99,642,450.00,702,87.70,0,0,0,0,1896.00
7897,0,all_other,0.09,15.91,7.60,0.00,702,238.96,0,0.00,6,0,0,1,2000.00
8438,0,educational,0.08,15.67,8.10,0.00,747,570.00,0,0.00,0,0,0,0,3300.00
8171,0,all_other,0.07,49.72,8.16,5.14,752,930.04,506,5.90,0,0,0,0,3500.00
8352,0,all_other,0.11,49.72,8.19,11.33,682,1068.00,3757,52.90,1,0,0,1,3600.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5499,1,all_other,0.13,840.83,13.71,1.16,747,4890.00,30706,44.00,1,0,0,0,900000.00
6371,1,all_other,0.08,312.19,14.00,0.80,807,11700.00,7729,12.90,0,0,0,0,1199999.99
5493,1,debt_consolidation,0.08,206.05,14.12,0.62,782,4709.96,20,0.10,2,0,0,0,1362000.01
5791,1,major_purchase,0.07,198.78,14.18,0.00,772,5071.00,2926,13.00,0,0,0,0,1440000.00
653,1,debt_consolidation,0.12,281.84,14.53,0.13,672,1293.04,8747,51.80,1,0,0,0,2039784.00

In [73]:
pd.options.display.float_format = '{:.2f}'.format

In [74]:
df.sort_values('ingreso_real')

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,ingreso_real
7822,0,debt_consolidation,0.17,64.38,7.55,18.99,642,450.00,702,87.70,0,0,0,0,1896.00
7897,0,all_other,0.09,15.91,7.60,0.00,702,238.96,0,0.00,6,0,0,1,2000.00
8438,0,educational,0.08,15.67,8.10,0.00,747,570.00,0,0.00,0,0,0,0,3300.00
8171,0,all_other,0.07,49.72,8.16,5.14,752,930.04,506,5.90,0,0,0,0,3500.00
8352,0,all_other,0.11,49.72,8.19,11.33,682,1068.00,3757,52.90,1,0,0,1,3600.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5499,1,all_other,0.13,840.83,13.71,1.16,747,4890.00,30706,44.00,1,0,0,0,900000.00
6371,1,all_other,0.08,312.19,14.00,0.80,807,11700.00,7729,12.90,0,0,0,0,1199999.99
5493,1,debt_consolidation,0.08,206.05,14.12,0.62,782,4709.96,20,0.10,2,0,0,0,1362000.01
5791,1,major_purchase,0.07,198.78,14.18,0.00,772,5071.00,2926,13.00,0,0,0,0,1440000.00
653,1,debt_consolidation,0.12,281.84,14.53,0.13,672,1293.04,8747,51.80,1,0,0,0,2039784.00

In [75]:
df['fico'].corr(df['int.rate'])

np.float64(-0.7148207714193584)

In [76]:
df['not.fully.paid'].mean()

np.float64(0.16005429108373356)

In [77]:
condiciones = [df['fico'] > 720, df['fico'].between(660,719), df['fico'] < 660]
etiquetas = ['Prime', 'Standard', 'Subprime']

df['Categoria'] = np.select(condiciones, etiquetas, default='Desconocido')

In [78]:
df

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,ingreso_real,Categoria
0,1,debt_consolidation,0.12,829.10,11.35,19.48,737,5639.96,28854,52.10,0,0,0,0,85000.00,Prime
1,1,credit_card,0.11,228.22,11.08,14.29,707,2760.00,33623,76.70,0,0,0,0,65000.00,Standard
2,1,debt_consolidation,0.14,366.86,10.37,11.63,682,4710.00,3511,25.60,1,0,0,0,32000.00,Standard
3,1,debt_consolidation,0.10,162.34,11.35,8.10,712,2699.96,33667,73.20,1,0,0,0,85000.00,Standard
4,1,credit_card,0.14,102.92,11.30,14.97,667,4066.00,4740,39.50,0,1,0,0,80800.00,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9573,0,all_other,0.15,344.76,12.18,10.39,672,10474.00,215372,82.10,2,0,0,1,195000.00,Standard
9574,0,all_other,0.13,257.70,11.14,0.21,722,4380.00,184,1.10,5,0,0,1,69000.00,Prime
9575,0,debt_consolidation,0.11,97.81,10.60,13.09,687,3450.04,10036,82.90,8,0,0,1,40000.00,Standard
9576,0,home_improvement,0.16,351.58,10.82,19.18,692,1800.00,0,3.20,5,0,0,1,50000.00,Standard
9577,0,debt_consolidation,0.14,853.43,11.26,16.28,732,4740.00,37879,57.00,6,0,0,1,78000.00,Prime

In [79]:
df.groupby('Categoria')['not.fully.paid'].mean()

Categoria
Prime      0.10
Standard   0.18
Subprime   0.31
Name: not.fully.paid, dtype: float64

In [80]:
tabla = pd.pivot_table(df, values='int.rate', index='purpose', columns='Categoria', aggfunc='mean')
tabla

Categoria           Prime  Standard  Subprime
purpose
all_other            0.10      0.13      0.15
credit_card          0.10      0.13      0.15
debt_consolidation   0.10      0.14      0.15
educational          0.10      0.13      0.15
home_improvement     0.10      0.13      0.16
major_purchase       0.10      0.13      0.14
small_business       0.12      0.15      0.16

In [81]:
df[(df['Categoria'] == 'Subprime') & (df['dti'] > 20) & (df['inq.last.6mths'] > 5) & (df['not.fully.paid'] == 0)]

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,ingreso_real,Categoria
8006,0,debt_consolidation,0.17,531.74,10.62,20.53,652,2880.00,1728,57.60,8,0,0,0,40800.00,Subprime
8052,0,debt_consolidation,0.18,72.17,10.70,28.73,647,4709.00,6076,79.90,6,1,0,0,44400.00,Subprime
8062,0,all_other,0.14,46.39,11.00,21.34,642,5880.00,25254,53.10,24,0,0,0,60000.00,Subprime
8109,0,debt_consolidation,0.16,286.73,10.52,22.25,647,4440.00,276,92.00,6,0,1,0,37000.00,Subprime
8265,0,all_other,0.18,129.20,10.43,27.42,647,3750.04,13156,25.60,10,0,0,0,34000.00,Subprime
8297,0,debt_consolidation,0.18,185.13,10.49,25.67,642,2880.00,5004,60.30,6,0,2,0,36000.00,Subprime
8356,0,credit_card,0.15,191.88,11.51,22.46,647,9089.00,70533,79.40,6,0,0,0,100000.00,Subprime
8398,0,home_improvement,0.16,153.80,10.54,24.71,652,3300.00,12160,48.60,14,0,0,0,37680.00,Subprime
8486,0,credit_card,0.15,207.47,10.78,22.13,657,8099.96,22512,57.90,6,0,0,0,48000.00,Subprime
8506,0,debt_consolidation,0.17,89.56,10.60,25.77,652,5609.96,28446,64.10,10,3,0,0,40000.00,Subprime
8522,0,debt_consolidation,0.18,411.99,11.46,20.48,652,7207.00,10705,44.60,7,1,1,0,95000.00,Subprime
8523,0,credit_card,0.17,182.70,10.70,26.78,657,1980.00,12061,89.30,8,0,0,0,44187.00,Subprime

In [82]:
#El Top 10 de la Deuda
#El banco quiere saber quiénes son los 10 clientes con el pago mensual (installment) más alto que además tengan un FICO por debajo de 700.

In [83]:
df[df['fico'] < 700].sort_values('installment', ascending=False).head(10)

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,ingreso_real,Categoria
9281,0,debt_consolidation,0.21,940.14,12.57,18.64,682,4589.96,18406,50.80,9,0,0,0,287777.00,Standard
9309,0,debt_consolidation,0.20,926.83,11.59,20.28,687,4320.96,14858,99.10,4,0,0,0,107700.00,Standard
9524,0,credit_card,0.19,922.42,11.56,19.81,662,3380.04,20622,76.40,5,0,0,0,105000.00,Standard
5479,1,credit_card,0.19,918.02,11.90,18.54,662,4890.00,46031,77.40,1,1,0,1,148000.00,Standard
7687,1,all_other,0.19,916.95,12.35,14.43,667,5970.04,39476,78.30,0,0,0,0,230000.00,Standard
6080,1,debt_consolidation,0.19,913.63,11.46,18.18,667,5160.00,15109,77.90,1,0,0,0,95000.00,Standard
9366,0,small_business,0.19,913.63,11.74,18.59,697,15271.00,182893,69.70,2,0,0,0,125000.00,Standard
4019,1,credit_card,0.19,910.44,11.70,24.97,672,4290.00,96565,88.90,0,0,0,0,120000.00,Standard
6848,1,debt_consolidation,0.18,909.25,10.90,10.04,672,3660.00,1066,20.50,0,0,0,1,54000.00,Standard
7424,1,debt_consolidation,0.18,907.60,12.37,7.28,672,6570.00,28897,46.90,1,1,0,1,235000.00,Standard

In [84]:
#Necesito saber si hay una diferencia real entre consolidar deudas y usar tarjetas de crédito.

#Misión: Crea un nuevo DataFrame llamado df_deudas que solo contenga las filas donde purpose sea igual a credit_card O debt_consolidation.

#Cálculo: Sobre ese nuevo DataFrame, agrupa por purpose y saca el promedio de int.rate.

In [85]:

df_deudas = pd.DataFrame(df[(df['purpose'] == 'credit_card') | (df['purpose'] == 'debt_consolidation')])

In [86]:
df_deudas.groupby('purpose')['int.rate'].mean()

purpose
credit_card          0.12
debt_consolidation   0.13
Name: int.rate, dtype: float64

In [87]:
##Vamos a identificar rápidamente quién está usando demasiado sus tarjetas de crédito.

#Misión: Crea una columna llamada ALERTA usando np.where.

#ógica: Si revol.util (utilización de crédito revolvente) es mayor a 80, la columna debe decir 'Crítico', de lo contrario debe decir 'Ok'.

In [88]:
df['Alerta'] = np.where(df['revol.util'] > 80, 'Critico', 'Ok')

print(df['Alerta'].value_counts())

Alerta
Ok         7989
Critico    1589
Name: count, dtype: int64

In [89]:
# Filtra críticos -> Agrupa por propósito -> Saca promedio de interés -> Ordena

In [90]:
reporte = df[df['Alerta'] == 'Critico'].groupby('purpose')['int.rate'].mean().sort_values(ascending=False)

In [91]:
#Muestra las últimas 3 filas del dataframe (no las primeras).

#Calcula el valor máximo de la columna installment.

#Filtra los clientes que tienen una tasa de interés (int.rate) mayor a 0.20.

In [92]:
df.tail(10)

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,ingreso_real,Categoria,Alerta
9568,0,all_other,0.20,37.06,10.65,22.17,667,5916.00,28854,59.80,6,0,1,0,42000.00,Standard,Ok
9569,0,home_improvement,0.14,823.34,12.43,3.62,722,3239.96,33575,83.90,5,0,0,1,250000.00,Prime,Critico
9570,0,all_other,0.17,113.63,10.65,28.06,672,3210.04,25759,63.80,5,0,0,1,42000.00,Standard,Ok
9571,0,all_other,0.16,161.01,11.23,8.00,677,7230.00,6909,29.20,4,0,1,1,75000.00,Standard,Ok
9572,0,debt_consolidation,0.16,69.98,10.11,7.02,662,8190.04,2999,39.50,6,0,0,1,24599.28,Standard,Ok
9573,0,all_other,0.15,344.76,12.18,10.39,672,10474.00,215372,82.10,2,0,0,1,195000.00,Standard,Critico
9574,0,all_other,0.13,257.70,11.14,0.21,722,4380.00,184,1.10,5,0,0,1,69000.00,Prime,Ok
9575,0,debt_consolidation,0.11,97.81,10.60,13.09,687,3450.04,10036,82.90,8,0,0,1,40000.00,Standard,Critico
9576,0,home_improvement,0.16,351.58,10.82,19.18,692,1800.00,0,3.20,5,0,0,1,50000.00,Standard,Ok
9577,0,debt_consolidation,0.14,853.43,11.26,16.28,732,4740.00,37879,57.00,6,0,0,1,78000.00,Prime,Ok

In [93]:
df['installment'].max()

940.14

In [94]:
df[df['int.rate'] > 0.20]

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,ingreso_real,Categoria,Alerta
2945,1,credit_card,0.21,902.54,11.69,20.92,667,6300.04,45414,98.30,0,1,0,0,119450.00,Standard,Critico
3713,1,small_business,0.20,623.40,11.45,5.36,667,4169.96,5848,24.30,3,3,0,1,94000.00,Standard,Ok
3991,1,small_business,0.20,623.40,11.00,21.34,662,3960.00,13337,59.00,0,1,1,1,60000.00,Standard,Ok
4731,1,small_business,0.20,186.26,10.82,6.00,672,5009.96,9814,59.50,1,0,1,1,50000.00,Standard,Ok
5274,1,credit_card,0.20,745.01,11.08,15.93,662,1560.00,4569,95.20,0,0,0,0,65000.00,Standard,Critico
5363,1,small_business,0.20,447.01,11.23,11.25,672,4530.00,3672,79.80,0,0,0,0,75000.00,Standard,Ok
5540,1,debt_consolidation,0.21,827.33,11.81,12.78,672,10169.96,62553,44.20,2,0,0,0,135000.00,Standard,Ok
5679,1,debt_consolidation,0.21,746.24,11.74,19.87,662,7920.00,90063,79.60,1,0,0,1,125000.00,Standard,Ok
5868,1,small_business,0.21,491.20,11.96,10.45,667,3538.00,14718,40.40,1,0,0,0,156000.00,Standard,Ok
6172,1,all_other,0.21,94.02,10.73,0.53,662,2029.04,2106,91.60,3,0,0,1,45600.00,Standard,Critico
6202,1,small_business,0.21,755.69,11.25,5.72,672,1440.00,500,83.30,1,0,0,0,76800.00,Standard,Critico
6432,1,small_business,0.21,299.43,10.31,8.12,677,1522.00,7327,86.20,2,0,0,1,30000.00,Standard,Critico
6517,1,debt_consolidation,0.21,816.14,11.03,15.45,667,3120.04,10190,98.90,1,0,0,0,62000.00,Standard,Critico
7313,1,debt_consolidation,0.21,771.28,11.14,24.52,662,3660.00,16491,99.90,1,1,0,1,69000.00,Standard,Critico
7361,1,home_improvement,0.20,893.85,11.70,2.35,667,6810.04,366,4.30,0,2,0,0,120000.00,Standard,Ok
8931,0,debt_consolidation,0.20,260.53,10.31,10.44,667,540.04,6402,80.00,4,0,1,1,30000.00,Standard,Ok
8994,0,major_purchase,0.20,91.19,9.31,3.16,667,570.00,242,9.70,6,0,0,0,11000.00,Standard,Ok
9008,0,small_business,0.20,65.14,9.90,2.40,667,540.00,806,17.10,5,0,0,0,20000.00,Standard,Ok
9042,0,small_business,0.20,735.06,13.30,14.39,672,7620.00,952013,99.00,6,0,0,0,600000.00,Standard,Critico
9049,0,all_other,0.20,130.27,10.82,15.65,672,600.00,390,26.00,4,0,0,1,50000.00,Standard,Ok
9063,0,educational,0.20,186.09,10.97,11.01,677,1559.96,0,0.00,8,0,0,0,58000.00,Standard,Ok
9196,0,small_business,0.20,902.54,11.92,15.19,687,3240.00,9943,80.80,4,0,0,1,150000.00,Standard,Critico
9202,0,all_other,0.20,55.88,10.57,17.32,677,1709.96,1513,37.80,10,0,0,0,39000.00,Standard,Ok
9248,0,home_improvement,0.21,681.19,13.02,14.10,697,3539.96,27286,56.50,10,1,0,0,450000.00,Standard,Ok
9263,0,debt_consolidation,0.20,745.01,12.39,6.46,697,4199.96,29182,97.90,9,0,0,0,240000.00,Standard,Critico
9281,0,debt_consolidation,0.21,940.14,12.57,18.64,682,4589.96,18406,50.80,9,0,0,0,287777.00,Standard,Ok
9286,0,small_business,0.21,827.33,12.30,10.81,667,4860.00,109901,66.50,4,0,0,1,220000.00,Standard,Ok
9328,0,small_business,0.21,94.47,11.38,5.21,687,12150.00,52702,41.10,6,2,0,0,87240.00,Standard,Ok
9337,0,debt_consolidation,0.21,187.14,12.09,0.17,707,4233.96,444,82.80,10,0,0,0,178000.00,Standard,Critico
9346,0,debt_consolidation,0.21,340.06,11.41,10.24,682,1452.00,6089,45.10,10,0,0,0,90000.00,Standard,Ok
9372,0,small_business,0.21,188.93,11.00,0.36,662,3660.04,581,12.10,5,2,0,0,60000.00,Standard,Ok
9409,0,debt_consolidation,0.21,300.85,11.55,17.12,667,8903.04,53338,41.30,6,1,0,0,103625.00,Standard,Ok
9459,0,small_business,0.21,898.27,11.74,16.62,762,4231.04,0,0.00,9,0,0,0,125000.00,Prime,Ok
9476,0,debt_consolidation,0.21,526.73,10.92,13.81,662,4110.04,13020,33.00,4,0,0,0,55000.00,Standard,Ok
9531,0,major_purchase,0.20,149.01,10.60,12.39,677,3140.04,200,13.30,10,3,0,0,40000.00,Standard,Ok
9549,0,home_improvement,0.22,729.70,11.88,8.63,667,8280.04,55442,66.90,9,0,1,1,144000.00,Standard,Ok
9566,0,all_other,0.22,551.08,11.00,24.06,662,1800.00,16441,49.80,9,0,0,1,60000.00,Standard,Ok

In [95]:
from sklearn.model_selection import train_test_split

y = df['not.fully.paid']

features = [
    'int.rate',          # Tasa de interés
    'installment',       # Cuota mensual
    'log.annual.inc',    # Ingreso anual (log)
    'dti',               # Relación deuda/ingreso
    'fico',              # Score de crédito FICO
    'inq.last.6mths',    # Consultas recientes a centrales de riesgo
    'revol.util'         # Uso de su cupo de crédito rotativo
]

X = df[features]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("¡Variables listas!")
print(f"Muestras de entrenamiento: {X_train.shape[0]}")
print(f"Muestras de prueba: {X_test.shape[0]}")

¡Variables listas!
Muestras de entrenamiento: 7662
Muestras de prueba: 1916

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

modelo_logit = LogisticRegression(solver='liblinear', random_state=42)


modelo_logit.fit(X_train, y_train)


y_pred = modelo_logit.predict(X_test)

print("¡Modelo entrenado y predicciones realizadas!")

¡Modelo entrenado y predicciones realizadas!

In [97]:
print("--- Informe de Clasificación ---")
print(classification_report(y_test, y_pred))


print("--- Matriz de Confusión ---")
print(confusion_matrix(y_test, y_pred))

--- Informe de Clasificación ---
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1611
           1       0.56      0.02      0.03       305

    accuracy                           0.84      1916
   macro avg       0.70      0.51      0.47      1916
weighted avg       0.80      0.84      0.77      1916

--- Matriz de Confusión ---
[[1607    4]
 [ 300    5]]

In [98]:
# Re-entrenamos el modelo con peso balanceado
modelo_logit_bal = LogisticRegression(solver='liblinear', class_weight='balanced', random_state=42)
modelo_logit_bal.fit(X_train, y_train)

y_pred_bal = modelo_logit_bal.predict(X_test)

print("--- Informe de Clasificación (BALANCEADO) ---")
print(classification_report(y_test, y_pred_bal))

print("--- Nueva Matriz de Confusión ---")
print(confusion_matrix(y_test, y_pred_bal))

--- Informe de Clasificación (BALANCEADO) ---
              precision    recall  f1-score   support

           0       0.90      0.62      0.74      1611
           1       0.24      0.62      0.34       305

    accuracy                           0.62      1916
   macro avg       0.57      0.62      0.54      1916
weighted avg       0.79      0.62      0.67      1916

--- Nueva Matriz de Confusión ---
[[1005  606]
 [ 117  188]]